name: Development branches

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: maven

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4 -ntp

#      - name: Upload test coverage to Codacy
#        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
#        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
#        env:
#          CODACY_PROJECT_TOKEN: "${{secrets.CODACY_PROJECT_TOKEN}}"
